title: JinPing Zou's Homepage
page-top-title: JinPing Zou
top-section-bg-text: Mathematics and Scientific Computing
home-subtitle: JinPing Zou&ensp;|&ensp;邹金坪
copyright-text: '&copy; JinPing Zou 2023-2025. All Rights Reserved.'
